// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxddP5QRCVD2cKajDlJcDL-MUQiPmPnU',
    appId: '1:716195596549:web:0feaafc5b63c2ec7170f6c',
    messagingSenderId: '716195596549',
    projectId: 'vinayak-ai',
    authDomain: 'vinayak-ai.firebaseapp.com',
    storageBucket: 'vinayak-ai.firebasestorage.app',
    measurementId: 'G-LRJ54XBCBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANR8vRIV-r8UjGMc8c2CjzlGKuLv0L0Ro',
    appId: '1:716195596549:android:1e8b51ff04c013b4170f6c',
    messagingSenderId: '716195596549',
    projectId: 'vinayak-ai',
    storageBucket: 'vinayak-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1TyBW79aAZSSX-mOGQewVQCvJBJxV7do',
    appId: '1:716195596549:ios:cb727b5f4226a57f170f6c',
    messagingSenderId: '716195596549',
    projectId: 'vinayak-ai',
    storageBucket: 'vinayak-ai.firebasestorage.app',
    iosBundleId: 'com.example.vinayakAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1TyBW79aAZSSX-mOGQewVQCvJBJxV7do',
    appId: '1:716195596549:ios:cb727b5f4226a57f170f6c',
    messagingSenderId: '716195596549',
    projectId: 'vinayak-ai',
    storageBucket: 'vinayak-ai.firebasestorage.app',
    iosBundleId: 'com.example.vinayakAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXxddP5QRCVD2cKajDlJcDL-MUQiPmPnU',
    appId: '1:716195596549:web:c5c45a9a81a9e3b0170f6c',
    messagingSenderId: '716195596549',
    projectId: 'vinayak-ai',
    authDomain: 'vinayak-ai.firebaseapp.com',
    storageBucket: 'vinayak-ai.firebasestorage.app',
    measurementId: 'G-C00BSWT22H',
  );
}
